### ISSUE TITLE
Additional color palettes

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/palette#14]
Users have requested the Material palette, and I could see something like Tango, Pop!, etc. being useful.

One way of supporting this is to read arbitrary palette files. Barring that, a static notebook with a few sane defaults might work, but a UI that could support arbitrary palettes in the future might be better.

**Comment by leonardomilano** [comment]
So few colors...
More
Please

**Comment by Hedronmx** [comment]
I would love the option to add our custom palletes

**Comment by cassidyjames** [comment]
I think this might get axed from Palette. The idea of Palette is to be an easy source for the official elementary palette, which means I can do interesting features like Gtk.CSS color constants. Other palettes won't have an equivalent for those, so I'm not sure how I'd support the features I want to develop while also supporting those.
