### ISSUE TITLE
Add Mint & Bubblegum

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [cassidyjames/palette#48]

**Comment by 4jNsY6fCVqZv** [comment]
I'd like to contribute something. It would be my first contribution to a project ever. Might need some feedback from you then. Could you imagine that?

**Comment by 4jNsY6fCVqZv** [comment]
I would like to work on this issue to contribute a solution. It would be my first contribution to a project ever. Might need some feedback from you then. How do you feel about it?

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv sorry I missed this one! I am working on it now. :smile:

**Comment by 4jNsY6fCVqZv** [comment]
Thanks and also a pity, I want to learn something!

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv you can still review the linked pull request to learn. :smile:

**Comment by 4jNsY6fCVqZv** [comment]
@cassidyjames Yes yes, so I'm trying to review an already merged patch. :smile:
