### ISSUE TITLE
Better Icon

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/palette#7]
I don't currently have a good icon. Some sort of painter's palette icon with the bright colors might work.

**Comment by cassidyjames** [comment]
Working on this for now:

![wip](https://cdn.rawgit.com/cassidyjames/palette/98d625db4c273e1736ddd2b42d760630aceaa176/data/icons/64/com.github.cassidyjames.palette.svg)

Contributions welcome :joy:

**Comment by micahilbery** [comment]
![16](https://user-images.githubusercontent.com/10608836/38530634-3b243032-3c31-11e8-99c8-ea4c49cd0513.png) ![24](https://user-images.githubusercontent.com/10608836/38531324-ea829048-3c34-11e8-8893-b7679544dc66.png) ![32](https://user-images.githubusercontent.com/10608836/38532273-abdcceda-3c39-11e8-8cca-bf2c7166b094.png) ![48](https://user-images.githubusercontent.com/10608836/38530640-3eaffbbe-3c31-11e8-8750-39e5216da00a.png) ![64](https://user-images.githubusercontent.com/10608836/38530641-451717ee-3c31-11e8-9bf9-2eacc58d8813.png) ![128](https://user-images.githubusercontent.com/10608836/38530647-4b624cb8-3c31-11e8-9c98-97ff981fcf49.png)
- [x] 16px
- [x] 24px
- [x] 32px
- [x] 48px
- [x] 64px
- [x] 128px

**Comment by cassidyjames** [comment]
@micahilbery loving 'em!
